apiVersion: 1

deleteDatasources:
  - name: Prometheus
    orgId: 1 
  - name: Loki
    orgId: 1
  - name: Jaeger
    orgId: 1
  - name: Alertmanager
    orgId: 1

datasources:
  - name: Prometheus
    type: prometheus
    access: proxy 
    url: http://prometheus:9090 
    uid: prom 
    isDefault: true 
    editable: false

  - name: Loki
    type: loki
    access: proxy
    url: http://loki:3100 
    uid: loki 
    editable: false
    jsonData:
      derivedFields:
        - datasourceUid: jaeger 
          matcherRegex: (?:"traceid"|trace_id|traceID)[":\s=]+"?([0-9a-fA-F]{32}|[0-9a-fA-F]{16})"?
          name: TraceID
          url: '$${__value.raw}' 
          # Optional: Use this if the link should go to the Jaeger search UI directly
          # url: '/explore?orgId=1&left=["now-1h","now","Jaeger",{"query":"$${__value.raw}"}]'

  - name: Jaeger
    type: jaeger
    access: proxy
    url: http://jaeger:16686 
    uid: jaeger 
    editable: false
    jsonData:
      tracesToLogsV2:
        datasourceUid: 'loki'
        tags: ['job', 'instance', 'pod', 'namespace']
        mappedTags: [{ key: 'service.name', value: 'service' }] 
        spanStartTimeShift: '10s'
        spanEndTimeShift: '10s'
        filterByTraceID: true
        filterBySpanID: false
        query: '{$$__tags} | json | line_format "{{ .message }}" | trace_id="$${__trace.traceId}"'
      tracesToMetrics:
        datasourceUid: 'prom'
        tags: [{ key: 'service.name', value: 'job' }, { key: 'span.kind' }] # Tags to map (adjust as needed)
        queries:
          - name: 'Request Rate'
            query: 'sum(rate(traces_spanmetrics_calls_total{$$__tags}[5m])) by (span_kind)'
          - name: 'Error Rate'
            query: 'sum(rate(traces_spanmetrics_calls_total{status_code="ERROR", $$__tags}[5m])) by (span_kind)'
          - name: 'Request Latency (P95)'
            query: 'histogram_quantile(0.95, sum(rate(traces_spanmetrics_latency_bucket{$$__tags}[5m])) by (le, span_kind))'
        spanStartTimeShift: '10s'
        spanEndTimeShift: '10s'
      nodeGraph:
        enabled: true

  - name: Alertmanager
    type: alertmanager
    access: proxy
    url: http://alertmanager:9093 
    uid: alertmanager 
    jsonData:
      implementation: 'prometheus'
    editable: false 

