{{- if (and .Values.apiKestrelCertVolume.enabled (not .Values.azure.enabled) .Values.secrets.apiKestrelCertPassword.create) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.apiKestrelCertVolume.name }}
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "bjj-app.labels" . | nindent 4 }}
type: Opaque
data:
  aspnetapp.pfx: {{ .Values.apiKestrelCertVolume.value | quote }}
{{- end }}