apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "bjj-app.frontend.fullname" . }}-nginx-config
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "bjj-app.labels" . | nindent 4 }}
    app.kubernetes.io/component: frontend
data:
  nginx.conf: |
    {{- .Values.frontendNginxConfig | nindent 4 }}
