apiVersion: v1
kind: Service
metadata:
  name: {{ include "bjj-app.frontend.fullname" . }}
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "bjj-app.labels" . | nindent 4 }}
    app.kubernetes.io/component: frontend
spec:
  type: {{ .Values.service.frontend.type }}
  ports:
    - port: {{ .Values.service.frontend.port }}
      targetPort: http
      protocol: TCP
      name: http
    {{- if .Values.service.frontend.httpsPort }}
    - port: {{ .Values.service.frontend.httpsPort }}
      targetPort: https
      protocol: TCP
      name: https
    {{- end }}
  selector:
    {{- include "bjj-app.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: frontend
