apiVersion: v1
kind: Service
metadata:
  name: {{ include "bjj-app.mongodb.fullname" . }}
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "bjj-app.labels" . | nindent 4 }}
    app.kubernetes.io/component: mongodb
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.environment.mongodb.MONGODB_PORT }}
      targetPort: mongo
      protocol: TCP
      name: mongo
  selector:
    {{- include "bjj-app.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: mongodb
