apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "bjj-app.mongodb.fullname" . }}-pvc
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "bjj-app.labels" . | nindent 4 }}
    app.kubernetes.io/component: mongodb
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.mongodbVolume.size }}
  storageClassName: {{ .Values.mongodbVolume.storageClassName }}