x-defaults: &default-service
  platform: linux/arm64
  restart: unless-stopped
  networks:
    - bjj-network
  deploy:
    resources:
      limits:
        cpus: '0.50'
        memory: 512M
      reservations:
        cpus: '0.25'
        memory: 256M

x-healthcheck-curl: &healthcheck-curl
  interval: 30s
  timeout: 10s
  retries: 3
  start_period: 10s

x-healthcheck-wget: &healthcheck-wget
  interval: 10s
  timeout: 5s
  retries: 5
  start_period: 10s

services:
  api:
    <<: *default-service
    profiles: ["app"] 
    container_name: api
    ports:
      - "5003:80"
      - "5001:443"
    environment:
      - ASPNETCORE_ENVIRONMENT=${ASPNETCORE_ENVIRONMENT}
      - ASPNETCORE_URLS=${ASPNETCORE_URLS}
      - ASPNETCORE_HTTP_PORT=${ASPNETCORE_HTTP_PORT}
      - ASPNETCORE_HTTPS_PORT=${ASPNETCORE_HTTPS_PORT}
      - ASPNETCORE_Kestrel__Certificates__Default__Password=${ASPNETCORE_KESTREL_CERT_PASSWORD}
      - ASPNETCORE_Kestrel__Certificates__Default__Path=${ASPNETCORE_KESTREL_CERT_PATH}
      - ConnectionStrings__Mongodb=mongodb://${MONGODB_USER:-admin}:${MONGODB_PASSWORD:-password}@${MONGODB_HOST:-mongodb}:${MONGODB_PORT:-27017}/${MONGODB_DB:-Mongodb}?authSource=admin&authMechanism=SCRAM-SHA-256
      - CorsOptions__AllowedOrigins=${CORS_ORIGINS}
      - Serilog__WriteTo__1__Args__endpoint=${OTEL_EXPORTER_OTLP_ENDPOINT}
      - Serilog__Properties__Application=${OTEL_SERVICE_NAME}
      - OTEL_EXPORTER_OTLP_ENDPOINT=${OTEL_EXPORTER_OTLP_ENDPOINT}
      - OTEL_RESOURCE_ATTRIBUTES__service.name=${OTEL_SERVICE_NAME}
    volumes:
      - ./logs:/app/logs
      - ./certs:/https:ro
    secrets:
      - cert_password
      - mongodb_password
    depends_on:
      mongodb:
        condition: service_healthy
    healthcheck:
      <<: *healthcheck-curl
      test: ["CMD", "curl", "-f", "-k", "https://localhost:443/health"]

  frontend:
    <<: *default-service
    profiles: ["app"]
    container_name: web
    ports:
      - "60742:80"
      - "60743:443"
    environment:
      # - BROWSER=${BROWSER}
      - NODE_ENV=${NODE_ENV}
      - PORT=${PORT}
      - SERVICES_API_HTTP_0=${SERVICES_API_HTTP_0}
      - SERVICES_API_HTTPS_0=${SERVICES_API_HTTPS_0}
      # - VITE_APP_API_URL=${VITE_APP_API_URL}
      # - VITE_APP_URL=${VITE_APP_URL}
    volumes: 
        - ${BASE_PATH}/certs/aspnetapp.crt:/etc/nginx/certs/aspnetapp.crt:ro
        - ${BASE_PATH}/certs/aspnetapp.key:/etc/nginx/certs/aspnetapp.key:ro
    depends_on:
      api:
        condition: service_healthy
    healthcheck:
      <<: *healthcheck-curl
      test: ["CMD", "curl", "-f", "-k", "https://localhost:443/health"]

  # frontend:
  #   <<: *default-service
  #   profiles: ["app"]
  #   container_name: web
  #   volumes:
  #     - frontend_dist_volume:/app/dist
  #   command: ["npm", "run", "build"]
  #   deploy: 
  #     resources:
  #       limits:
  #         cpus: '0.75'
  #         memory: 2048M
  #       reservations:
  #         cpus: '0.50'
  #         memory: 1024M 

  # nginx:
  #   <<: *default-service
  #   profiles: ["app"]
  #   image: nginx:latest
  #   container_name: nginx
  #   ports:
  #     - "80:80"    
  #     - "443:443"
  #   volumes:
  #     - ${BASE_PATH}/infra/nginx/default.conf.template:/etc/nginx/templates/default.conf.template
  #     - ${BASE_PATH}/certs/aspnetapp.crt:/etc/nginx/certs/aspnetapp.crt
  #     - ${BASE_PATH}/certs/aspnetapp.key:/etc/nginx/certs/aspnetapp.key
  #     - ${BASE_PATH}/logs/nginx:/var/log/nginx
  #     - frontend_dist_volume:/usr/share/nginx/html:ro
  #   environment:
  #     - PORT=${PORT}
  #     - SERVICES_API_HTTP_0=${SERVICES_API_HTTP_0}
  #     - SERVICES_API_HTTPS_0=${SERVICES_API_HTTPS_0}
  #   depends_on:
  #     frontend:
  #       condition: service_completed_successfully
  #     api:
  #       condition: service_healthy
  #   healthcheck:
  #     <<: *healthcheck-curl
  #     test: ["CMD", "curl", "-f", "-k", "https://localhost:443/health"]

  mongodb:
    <<: *default-service
    profiles: ["app"]
    image: mongo:latest
    container_name: mongodb
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGODB_USER:-admin}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGODB_PASSWORD}
    volumes:
      - mongodb_data:/data/db
    secrets:
      - mongodb_password
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongosh localhost:27017/test --quiet
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s

volumes:
  mongodb_data:
  frontend_dist_volume:

secrets:
  cert_password:
    file: ./secrets/cert_password.txt
  mongodb_password:
    file: ./secrets/mongodb_password.txt

networks:
  bjj-network:
    driver: bridge
