services:
  api:
    build:
      context: .
      dockerfile: ./src/BjjEire.Api/Dockerfile
    environment:
      ASPNETCORE_ENVIRONMENT: "Development"

  frontend:
    build:
      context: .
      dockerfile: src/bjjeire-app/Dockerfile
      args:
        SERVICES_API_HTTP_0: ${SERVICES_API_HTTP_0}
        SERVICES_API_HTTPS_0: ${SERVICES_API_HTTPS_0}
        PORT: ${PORT}
