services:
  api:
    build:
      context: .
      dockerfile: ./src/BjjEire.Api/Dockerfile
    environment:
      ASPNETCORE_ENVIRONMENT: "Development"
      OTEL_EXPORTER_OTLP_ENDPOINT: ""

  frontend:
    build:
      context: .
      dockerfile: src/bjjeire-app/Dockerfile
      args:
        SERVICES_API_HTTP_0: ${SERVICES_API_HTTP_0}
        SERVICES_API_HTTPS_0: ${SERVICES_API_HTTPS_0}
        VITE_APP_MSAL_CLIENT_ID: ${VITE_APP_MSAL_CLIENT_ID}
        VITE_APP_MSAL_AUTHORITY: ${VITE_APP_MSAL_AUTHORITY}
        VITE_APP_MSAL_API_SCOPE: ${VITE_APP_MSAL_API_SCOPE}
        VITE_APP_CF_BEACON_TOKEN: ${VITE_APP_CF_BEACON_TOKEN}
    volumes:
      - ./tools/images/processed:/srv/images:ro

  seeder:
    build:
      context: .
      dockerfile: ./src/BjjEire.Seeder/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__Mongodb=mongodb://${MONGODB_USER:-admin}:${MONGODB_PASSWORD:-password}@mongodb:${MONGODB_PORT:-27017}/${MONGODB_DB:-Mongodb}?authSource=admin&authMechanism=SCRAM-SHA-256
    depends_on:
      mongodb:
        condition: service_healthy
    networks:
      - bjj-network
    profiles:
      - seed
    restart: "no"

