services:
  api:
    image: ${GHCR_REGISTRY:-ghcr.io}/${GHCR_OWNER}/bjjeire-api:${API_IMAGE_TAG:-latest}
    pull_policy: always
    environment:
      SPRING_PROFILES_ACTIVE: "staging"

  frontend:
    image: ${GHCR_REGISTRY:-ghcr.io}/${GHCR_OWNER}/bjjeire-frontend:${FRONTEND_IMAGE_TAG:-latest}
    pull_policy: always
