  steps:
    - task: AzureCLI@2
      displayName: 'Azure Login (Workload Identity Federation)'
      inputs:
        azureSubscription: 'AzureServiceConnectionWIF'
        scriptType: 'bash'  
        scriptLocation: 'inlineScript'
        inlineScript: |
            echo "Attempting to log into Azure..."
            az account show > /dev/null 2>&1
            if [ $? -eq 0 ]; then
                echo "##vso[task.logissue type=warning]Already logged in, skipping re-authentication."
            else
                echo "Successfully logged into Azure via Service Connection."
            fi
      env:
        AZURE_CLIENT_ID: $(AZURE-APP-CLIENT-ID)
        AZURE_TENANT_ID: $(AZURE-TENANT-ID)
        AZURE_SUBSCRIPTION_ID: $(AZURE-SUBSCRIPTION-ID)