parameters:
  - name: imageName
    type: string
  - name: dockerfile
    type: string
  - name: tags
    type: string
  - name: arguments
    type: string

steps:
  - task: Docker@2
    displayName: 'Build ${{ parameters.imageName }}'
    inputs:
      command: 'build'
      repository: '${{ parameters.imageName }}'
      dockerfile: '${{ parameters.dockerfile }}'
      containerRegistry: '$(AZURE_CONTAINER_REGISTRY_SERVICE_CONNECTION)'
      tags: ${{ parameters.tags }}
      buildContext: '.'
      arguments: ${{ parameters.arguments }}
    env:
      DOCKER_BUILDKIT: 1

  - task: Docker@2
    displayName: 'Push ${{ parameters.imageName }}'
    inputs:
      command: 'push'
      repository: '${{ parameters.imageName }}'
      containerRegistry: '$(AZURE_CONTAINER_REGISTRY_SERVICE_CONNECTION)'
      tags: ${{ parameters.tags }}
    env:
      DOCKER_BUILDKIT: 1
  # - task: Docker@2
  #   displayName: 'Build and Push ${{ parameters.imageName }}'
  #   inputs:
  #     command: 'buildAndPush'
  #     repository: '${{ parameters.imageName }}'
  #     dockerfile: '${{ parameters.dockerfile }}'
  #     containerRegistry: '$(AZURE_CONTAINER_REGISTRY_SERVICE_CONNECTION)'
  #     tags: ${{ parameters.tags }}
  #     buildContext: '.'
  #     arguments: ${{ parameters.arguments }}
  # #   env:
  #     DOCKER_BUILDKIT: 1 