parameters:
  - name: dotnetVersion
    type: string
    default: '9.x'
  - name: testArtifactName
    type: string
    default: ''
  - name: testAssemblyPattern
    type: string
    default: '*Tests.dll'
  - name: testResultsNamePrefix
    type: string
    default: 'TestResults'
  - name: testFilterCriteria
    type: string
    default: ''
  - name: downloadPath
    type: string
    default: '$(Build.SourcesDirectory)/test_artifacts'

steps:
  - task: UseDotNet@2
    displayName: 'Setup .NET SDK ${{ parameters.dotnetVersion }}'
    inputs:
      version: ${{ parameters.dotnetVersion }}
      packageType: 'sdk'

  - task: DownloadPipelineArtifact@2
    displayName: 'Download Test Artifact - ${{ parameters.testArtifactName }}'
    inputs:
      buildType: 'current'
      artifact: ${{ parameters.testArtifactName }}
      :  ${{ parameters.testAssemblyPattern }}
      targetPath: '${{ parameters.downloadPath }}/${{ parameters.testArtifactName }}'

  - script: |
      TEST_RESULTS_DIR="$(Agent.TempDirectory)/TestResults/${{ parameters.testResultsNamePrefix }}"
      mkdir -p "$TEST_RESULTS_DIR"

      dotnet test "**\*Tests.dll" \
      --logger "trx;LogFileName=${{ parameters.testResultsNamePrefix }}.trx" \
      --results-directory "$TEST_RESULTS_DIR" \
      --filter "${{ parameters.testFilterCriteria }}"
    displayName: 'Run Tests'
    workingDirectory: '${{ parameters.downloadPath }}/${{ parameters.testArtifactName }}'

  # - task: DotNetCoreCLI@2
  #   displayName: 'Run Tests'
  #   inputs:
  #     command: 'test'
  #     pathToTestAssemblies: '**/*Tests.dll'
  #     workingDirectory: '${{ parameters.downloadPath }}/${{ parameters.testArtifactName }}'
  #     arguments: '--no-build --logger "trx;LogFileName=test-results.trx"'
  #     filter: ${{ parameters.testFilterCriteria }}
  #     rerunFailedTests: true
  #     rerunMaxAttempts: 2 

  - task: PublishTestResults@2
    displayName: 'Publish Test Results'
    condition: succeededOrFailed()
    inputs:
      testResultsFormat: 'VSTest'
      testResultsFiles: '**/*.trx'
      searchFolder: '$(Agent.TempDirectory)'
      mergeResults: true
      testRunTitle: '${{ parameters.testResultsNamePrefix }} Tests'
      failTaskOnFailedTests: true

  - task: PublishBuildArtifacts@1
    displayName: 'Upload Test Results Artifact'
    condition: succeededOrFailed()
    inputs:
      pathToPublish: '$(Agent.TempDirectory)/TestResults/${{ parameters.testResultsNamePrefix }}'
      artifactName: 'test_results_${{ parameters.testResultsNamePrefix }}'