parameters:
  - name: dotnetVersion
    type: string
    default: '6.x'
  - name: projectPath
    type: string
    default: ''
  - name: configuration
    type: string
    default: 'Release'
  - name: outputPath
    type: string
    default: ''
  - name: artifactName
    type: string
    default: ''

steps:
  - template: setup-dotnet.yml
    parameters:
      dotnetVersion: ${{ parameters.dotnetVersion }}

  - task: DotNetCoreCLI@2
    displayName: 'Restore Project Dependencies'
    inputs:
      command: 'restore'
      projects: '${{ parameters.projectPath }}'

  - task: DotNetCoreCLI@2
    displayName: 'Publish Project'
    inputs:
      command: 'publish'
      projects: '${{ parameters.projectPath }}'
      publishWebProjects: false
      zipAfterPublish: false
      arguments: '--configuration ${{ parameters.configuration }} --no-restore --output "${{ parameters.outputPath }}"'
  
  - task: PublishPipelineArtifact@1
    displayName: 'Publish ${{ parameters.artifactName }} artifacts'
    condition: and(succeeded(), ne('${{ parameters.artifactName }}', ''))
    inputs:
      targetPath: '${{ parameters.outputPath }}'
      artifact: ${{ parameters.artifactName }}
      publishLocation: 'pipeline'