parameters:
  - name: downloadPath
    type: string
    default: '$(Build.SourcesDirectory)/test_artifacts'

steps:
  - task: DownloadPipelineArtifact@2
    displayName: 'Download all workflow pipeline artifacts'
    inputs:
      buildType: 'current'
      patterns:  '**'
      targetPath: '${{ parameters.downloadPath }}'

  - task: PublishTestResults@2
    displayName: 'Publish Test Results Summary'
    condition: always()
    inputs:
      testResultsFormat: 'VSTest'
      testResultsFiles: '${{ parameters.downloadPath }}/**/*.trx'
      mergeResults: true 
      testRunTitle: 'Aggregated Test Results'