[auth.anonymous]
enabled = ${GF_AUTH_ANONYMOUS_ENABLED}
hide_version = true

[dashboards]
default_home_dashboard_path =${GF_DASHBOARDS_DEFAULT_HOME_DASHBOARD_PATH}
min_refresh_interval =${GF_DASHBOARDS_MIN_REFRESH_INTERVAL}

[database]
type = ${GF_DATABASE_TYPE}
host = ${GF_DATABASE_HOST}
name = ${GF_DATABASE_NAME}
user = ${GF_DATABASE_USER}
password = ${GF_DATABASE_PASSWORD}
ssl_mode = disable

[auth]
login_cookie_name = grafana_session 

[auth.session]
provider = ${GF_AUTH_SESSION_PROVIDER} 
provider_config = ${GF_AUTH_SESSION_PROVIDER_CONFIG} 
cookie_secure = true 

[server]
# protocol = https
# http_port = 3000
# domain = grafana.example.com  # Replace with your domain
root_url =${GF_SERVER_ROOT_URL}


[security]
admin_user = ${GF_SECURITY_ADMIN_USER}
admin_password = ${GF_SECURITY_ADMIN_PASSWORD}
# cookie_secure = true
# data_source_proxy_whitelist =  # Restrict data source access if needed

[log]
mode = ${GF_LOG_LEVEL}
level =${GF_LOG_MODE}

[remote_cache]
type = ${GF_REMOTE_CACHE_TYPE}
connstr = ${GF_REMOTE_CACHE_CONNSTR}

[unified_alerting]
enabled = true
# List of Grafana instances for HA (use service name; Docker DNS resolves to all replicas)
# ha_peers = grafana:9094
# Listen address for gossip protocol (0.0.0.0 to accept all interfaces)
# ha_listen_address = 0.0.0.0:9094
# Timeout for sending notifications (increase if high latency)
# ha_peer_timeout = 15s
# Optional: Use Redis for HA instead of gossip protocol
ha_redis_address = ${GF_UNIFIED_ALERTING_HA_REDIS_ADDRESS}
ha_redis_password = ${GF_UNIFIED_ALERTING_HA_REDIS_PASSWORD}
ha_redis_db = ${GF_UNIFIED_ALERTING_HA_REDIS_DB}
ha_redis_master_name = ${GF_UNIFIED_ALERTING_HA_REDIS_MASTER_NAME}

[metrics]
enabled = true
