parameters:
  dependsOn: []
  condition: 'succeeded()'
  name: ''
  pool:
    vmImage: 'ubuntu-latest'

jobs:
- job: ${{ parameters.name }}
  displayName: ${{ parameters.name }}
  timeoutInMinutes: 15
  cancelTimeoutInMinutes: 2
  dependsOn: ${{ parameters.dependsOn }}
  condition: ${{ parameters.condition }}
  pool: ${{ parameters.pool }}


  steps:
    - checkout: self

    # - task: UseNode@1
    #   displayName: 'Use Node.js $(NODE_VERSION)'
    #   inputs:
    #     versionSpec: '$(NODE_VERSION)'

    - script: |
        export NVM_DIR="/usr/local/lib/nvm"
        [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"
        [ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"

        # Install and use the desired Node.js version
        nvm install $(NODE_VERSION)
        nvm use $(NODE_VERSION)
        
        # Verify Node.js and npm versions
        node --version
        npm --version
        ls -la $(Build.SourcesDirectory)/$(REACT_APP_PATH)
      displayName: 'Log versions and list files (with nvm)'

    # - script: |
    #     node --version
    #     npm --version
    #     ls -la $(Build.SourcesDirectory)/$(REACT_APP_PATH)
    #   displayName: 'Log versions and list files'

    # - script: |
    #     npm cache clean --force
    #   displayName: 'Clear npm cache'
    #   workingDirectory: '$(Build.SourcesDirectory)/$(REACT_APP_PATH)'

    - task: Cache@2
      inputs:
        key: 'npm | "$(Agent.OS)" | $(Build.SourcesDirectory)/$(REACT_APP_PATH)/package-lock.json'
        path: '$(Build.SourcesDirectory)/$(REACT_APP_PATH)/node_modules'
        cacheHitVar: 'CACHE_RESTORED'
      displayName: 'Cache node_modules'

    - script: |
          npm ci
      displayName: 'Install Frontend Dependencies'
      workingDirectory: '$(Build.SourcesDirectory)/$(REACT_APP_PATH)'
      condition: ne(variables.CACHE_RESTORED, 'true')

    - script: |
          npm run build
      displayName: 'Build Frontend'
      workingDirectory: '$(Build.SourcesDirectory)/$(REACT_APP_PATH)'

    - script: |
        npx vitest run --reporter=junit --outputFile=$(Build.SourcesDirectory)/$(REACT_APP_PATH)/junit.xml
      displayName: 'Run Frontend Tests'
      workingDirectory: '$(Build.SourcesDirectory)/$(REACT_APP_PATH)'
      continueOnError: true

    - task: PublishTestResults@2
      displayName: 'Publish Frontend Test Results'
      inputs:
        testResultsFormat: 'JUnit'
        testResultsFiles: '$(Build.SourcesDirectory)/$(REACT_APP_PATH)/junit.xml'
        failTaskOnFailedTests: true
        condition: succeededOrFailed()

    # - task: PublishPipelineArtifact@1
    #   displayName: 'Publish Frontend Build Output'
    #   inputs:
    #     targetPath: '$(REACT_APP_PATH)/dist'
    #     artifact: 'frontend_dist'
    #     publishLocation: 'pipeline'