parameters:
  dependsOn: []
  condition: 'succeeded()'
  name: ''
  pool:
    vmImage: 'ubuntu-latest'

jobs:
- job: ${{ parameters.name }}
  displayName: ${{ parameters.name }}
  timeoutInMinutes: 15
  dependsOn: ${{ parameters.dependsOn }}
  condition: ${{ parameters.condition }}
  pool: ${{ parameters.pool }}

  steps:
    - checkout: self

    - template: ../tasks/setup-dotnet.yml
      parameters:
        dotnetVersion: $(DOTNET_VERSION)

    - script: |
        dotnet restore "$(SOLUTION_PATH)"
      displayName: 'Restore Dependencies'

    - script: |
        dotnet build "$(SOLUTION_PATH)" --configuration $(CONFIGURATION) --no-restore
      displayName: 'Build Solution'