parameters:
  dependsOn: []
  condition: 'succeeded()'
  name: ''
  pool:
    vmImage: 'ubuntu-latest'

jobs:
- job: ${{ parameters.name }}
  displayName: ${{ parameters.name }}
  timeoutInMinutes: 30
  cancelTimeoutInMinutes: 2
  dependsOn: ${{ parameters.dependsOn }}
  condition: ${{ parameters.condition }}
  pool: ${{ parameters.pool }}

  steps:
    - checkout: self
      fetchDepth: 0

    - template: ../tasks/generate-docker-tags.yml

    - template: ../tasks/docker-build-push.yml
      parameters:
        imageName: '$(API_IMAGE_NAME)'
        dockerfile: '$(Build.SourcesDirectory)/src/BjjEire.Api/Dockerfile'
        tags: $(generate_tags.apiImageTags)
        arguments: >
          --cache-from $(AZURE_CONTAINER_REGISTRY)/$(API_IMAGE_NAME):latest

    - template: ../tasks/docker-build-push.yml
      parameters:
        imageName: '$(FRONTEND_IMAGE_NAME)'
        dockerfile: '$(Build.SourcesDirectory)/src/bjjeire-app/Dockerfile'
        tags: $(generate_tags.frontendImageTags)
        arguments: >
          --cache-from $(AZURE_CONTAINER_REGISTRY)/$(FRONTEND_IMAGE_NAME):latest
          --build-arg SERVICES_API_HTTPS_0=$(SERVICES_API_HTTPS_0)
          --build-arg SERVICES_API_HTTP_0=$(SERVICES_API_HTTP_0)
          --build-arg NODE_ENV=$(NODE_ENV)

    - script: |
        docker logout $(AZURE_CONTAINER_REGISTRY)
      displayName: 'Docker Logout'
      condition: always()
