parameters:
  dependsOn: []
  condition: 'succeeded()'
  name: ''
  pool:
    vmImage: 'ubuntu-latest'

jobs:
- job: ${{ parameters.name }}
  displayName: ${{ parameters.name }}
  timeoutInMinutes: 20
  cancelTimeoutInMinutes: 2
  dependsOn: ${{ parameters.dependsOn }}
  condition: ${{ parameters.condition }}
  pool: ${{ parameters.pool }}

  steps:
    - checkout: self

    - template: ../tasks/publish-reports-task.yml
      parameters:
        downloadPath: '$(TEST_ARTIFACTS_DOWNLOAD_PATH)'

    - task: PowerShell@2
      displayName: 'Install Required PS Modules'
      inputs:
        targetType: 'inline'
        script: |
          Install-Module -Name Az.Storage -Repository PSGallery -Force -AcceptLicense -Scope CurrentUser
          Install-Module -Name Az.Data.Tables -Repository PSGallery -Force -AcceptLicense -Scope CurrentUser
    
    - task: PowerShell@2
      displayName: 'Log TestHistory'
      inputs:
        filePath: '$(System.DefaultWorkingDirectory)/.ado/scripts/Log-TestHistory.ps1'
        arguments: >
          -Organization "$(ORGANISATION_NAME)"
          -Project "$(System.TeamProject)"
          -BuildId "$(Build.BuildId)"
          -Pat $env:SYSTEM_ACCESSTOKEN
          -StorageConnectionString "$(TEST-RESULTS-SA-CONNECTION-STRING)"
          -ApiVersion "$(AZURE_API_VERSION)"
      env:
        SYSTEM_ACCESSTOKEN: $(System.AccessToken)
