parameters:
  dependsOn: []
  condition: 'succeeded()'
  name: ''
  pool:
    vmImage: 'ubuntu-latest'

jobs:
- job: ${{ parameters.name }}
  displayName: ${{ parameters.name }}
  timeoutInMinutes: 20
  cancelTimeoutInMinutes: 2
  dependsOn: ${{ parameters.dependsOn }}
  condition: ${{ parameters.condition }}
  pool: ${{ parameters.pool }}

  steps:
    - checkout: self

    - template: ../tasks/publish-reports-task.yml
      parameters:
        downloadPath: '$(TEST_ARTIFACTS_DOWNLOAD_PATH)'