parameters:
  dependsOn: []
  condition: 'succeeded()'
  name: ''
  pool:
    vmImage: 'ubuntu-latest'

jobs:
- job: ${{ parameters.name }}
  displayName: ${{ parameters.name }}
  timeoutInMinutes: 20
  cancelTimeoutInMinutes: 2
  dependsOn: ${{ parameters.dependsOn }}
  condition: ${{ parameters.condition }}
  pool: ${{ parameters.pool }}

  strategy:
    matrix:
      ApiUnitTests:
        testType: 'ApiUnitTests'
        artifactName: 'published_ApiUnitTests'
        projectPath: |
            **/*Api.UnitTests.csproj
      DomainUnitTests:
        testType: 'DomainUnitTests'
        artifactName: 'published_DomainUnitTests'
        projectPath: |
            **/*Domain.UnitTests.csproj
      ApplicationUnitTests:
        testType: 'ApplicationUnitTests'
        artifactName: 'published_ApplicationUnitTests'
        projectPath: |
            **/*Application.UnitTests.csproj
      InfrastructureUnitTests:
        testType: 'InfrastructureUnitTests'
        artifactName: 'published_InfrastructureUnitTests'
        projectPath: |
            **/*Infrastructure.UnitTests.csproj
      ApiIntegrationTests:
        testType: 'ApiIntegrationTests'
        artifactName: 'published_ApiIntegrationTests'
        projectPath: |
            **/*Api.IntegrationTests.csproj
      ApplicationIntegrationTests:
        testType: 'ApplicationIntegrationTests'
        artifactName: 'published_ApplicationIntegrationTests'
        projectPath: |
            **/*Application.IntegrationTests.csproj
    maxParallel: 6

  steps:
    - checkout: self

    - template: ../tasks/dotnet-publish.yml
      parameters:
        dotnetVersion: $(DOTNET_VERSION)
        projectPath: $(projectPath)
        configuration: $(CONFIGURATION) 
        outputPath: '$(Build.SourcesDirectory)/published_tests/$(artifactName)'
        artifactName: $(artifactName)
