parameters:
  dependsOn: []
  condition: 'succeeded()'
  name: ''
  pool:
    vmImage: 'ubuntu-latest'

jobs:
- job: ${{ parameters.name }}
  displayName: ${{ parameters.name }}
  timeoutInMinutes: 20
  cancelTimeoutInMinutes: 2
  dependsOn: ${{ parameters.dependsOn }}
  condition: ${{ parameters.condition }}
  pool: ${{ parameters.pool }}

  strategy:
      matrix:
        IntegrationTests:
          testType: 'IntegrationTests'
          testArtifactName: 'published_ApiIntegrationTests'
          testAssemblyPattern: |
              BjjEire.Api.IntegrationTests/**/*
          testFilterCriteria: 'TestCategory!=Ignore'

  steps:
    - checkout: self

    - template: ../tasks/dotnet-run-tests.yml
      parameters:
        dotnetVersion: $(DOTNET_VERSION)
        testArtifactName: $(testArtifactName)
        testAssemblyPattern: $(testAssemblyPattern)
        testResultsNamePrefix: $(testType)
        testFilterCriteria: '$(testFilterCriteria)'
        downloadPath: '$(TEST_ARTIFACTS_DOWNLOAD_PATH)'