parameters:
  dependsOn: []
  condition: 'succeeded()'
  name: ''
  pool:
    vmImage: 'ubuntu-latest'

jobs:
- job: ${{ parameters.name }}
  displayName: ${{ parameters.name }}
  timeoutInMinutes: 20
  cancelTimeoutInMinutes: 2
  dependsOn: ${{ parameters.dependsOn }}
  condition: ${{ parameters.condition }}
  pool: ${{ parameters.pool }}

  strategy:
      matrix:
        ApiUnitTests:
          testType: 'ApiUnitTests'
          testArtifactName: 'published_ApiUnitTests'
          testAssemblyPattern: |
              BjjEire.Api.UnitTests/**/*
        DomainUnitTests:
          testType: 'DomainUnitTests'
          testArtifactName: 'published_DomainUnitTests'
          testAssemblyPattern: |
              BjjEire.Domain.UnitTests/**/*
          testFilterCriteria: 'TestCategory!=Ignore'
        ApplicationUnitTests:
          testType: 'ApplicationUnitTests'
          testArtifactName: 'published_ApplicationUnitTests'
          testAssemblyPattern: |
              BjjEire.Application.UnitTests/**/*
          testFilterCriteria: 'TestCategory!=Ignore'
        InfrastructureUnitTests:
          testType: 'InfrastructureUnitTests'
          testArtifactName: 'published_InfrastructureUnitTests'
          testAssemblyPattern: |
              BjjEire.Infrastructure.UnitTests/**/*
          testFilterCriteria: 'TestCategory!=Ignore'
        ApiIntegrationTests:
          testType: 'ApiIntegrationTests'
          testArtifactName: 'published_ApiIntegrationTests'
          testAssemblyPattern: |
              BjjEire.Api.IntegrationTests/**/*
          testFilterCriteria: 'TestCategory!=Ignore'
        ApplicationIntegrationTests:
          testType: 'ApplicationIntegrationTests'
          testArtifactName: 'published_ApplicationIntegrationTests'
          testAssemblyPattern: |
              BjjEire.Application.IntegrationTests/**/*
          testFilterCriteria: 'TestCategory!=Ignore'

  steps:
    - checkout: self

    - template: ../tasks/dotnet-run-tests.yml
      parameters:
        dotnetVersion: $(DOTNET_VERSION)
        testArtifactName: $(testArtifactName)
        testAssemblyPattern: $(testAssemblyPattern)
        testResultsNamePrefix: $(testType)
        testFilterCriteria: '$(testFilterCriteria)'
        downloadPath: '$(TEST_ARTIFACTS_DOWNLOAD_PATH)'