stages:
  - stage: BuildAndTest
    displayName: 'Build and Test'
    jobs:
      # - template: ../templates/jobs/lint-check-job.yml

      - template: ../jobs/build-dotnet-solution-job.yml
        parameters:
          name: build_dotnet_solution
          displayName: 'Build .NET Solution'
       
      - template: ../jobs/publish-dotnet-test-projects-job.yml
        parameters:
          name: publish_dotnet_test_projects
          displayName: 'Publish .NET Test Projects'
          dependsOn: build_dotnet_solution
          condition: succeeded()

      - template: ../jobs/build-and-test-frontend-job.yml
        parameters:
          name: build_and_test_frontend
          displayName: 'Build and Test Frontend UI'

      - template: ../jobs/run-dotnet-tests-job.yml
        parameters:
          name: run_dotnet_tests
          displayName: 'Run .NET Tests'
          dependsOn: publish_dotnet_test_projects
          condition: succeeded()

      - template: ../jobs/publish-reports-job.yml
        parameters:
          name: publish_reports
          dependsOn: run_dotnet_tests
          condition: always()