stages:
  - stage: PackageAndPush
    displayName: 'Package and Push to ACR'
    dependsOn: BuildAndTest
    # condition: and(succeeded(), or(eq(variables['Build.Reason'], 'Push'), startsWith(variables['Build.SourceBranch'], 'refs/tags/v')))
    condition: succeeded()

    jobs:
      - template: ../jobs/package-and-push-job.yml
        parameters:
          name: package_and_push
          displayName: 'Package & Push to ACR'
