stages:
  - stage: PublishAndAnalyze
    displayName: 'Publish Results & Analyze Flakiness'
    dependsOn: BuildAndTest
    condition: succeededOrFailed()

    jobs:
      - template: ../jobs/log-test-history-job.yml
        parameters:
          name: log_test_history
          displayName: 'Package & Push to ACR'

  