export const gyms = {
  pageTitle: {
    all: 'All BJJ Gyms',
    prefix: 'BJJ Gyms in',
    foundPrefix: 'Found',
    foundSuffixSingular: 'gym.',
    foundSuffixPlural: 'gyms.',
  },
  filters: {
    countyLabel: 'Select County',
    allCountiesOption: 'All Counties',
  },
  hero: {
    tagline: 'Find BJJ Gyms Across Ireland',
    subtitle: 'Browse clubs, academies, and training centres near you.',
    imageAlt: 'BJJ Éire gym banner',
    ariaLabel: 'BJJ Éire — Find gyms across Ireland',
  },
  list: {
    ariaLabel: 'Brazilian Jiu-Jitsu gyms',
  },
  errors: {
    loadFailed: 'Failed to load gyms. Please try again.',
  },
  statusLabels: {
    active: 'Active',
    pendingApproval: 'Pending Approval',
    temporarilyClosed: 'Temporarily Closed',
    permanentlyClosed: 'Permanently Closed',
    openingSoon: 'Opening Soon',
    draft: 'Draft',
    rejected: 'Rejected',
    unknown: 'Unknown Status',
  },
  classCategoryLabels: {
    uncategorized: 'Uncategorized',
    bjjGiAllLevels: 'BJJ Gi (All Levels)',
    bjjNoGiAllLevels: 'BJJ No-Gi (All Levels)',
    womensOnly: "Women's Only",
    wrestling: 'Wrestling',
    muayThai: 'Muay Thai',
    boxing: 'Boxing',
    strengthTraining: 'Strength Training',
    yogaOrPilates: 'Yoga/Pilates',
    kidsBjj: 'Kids BJJ',
    bjjGiFundamentals: 'BJJ Gi (Fundamentals)',
    bjjGiAdvanced: 'BJJ Gi (Advanced)',
    bjjNoGiFundamentals: 'BJJ No-Gi (Fundamentals)',
    bjjNoGiAdvanced: 'BJJ No-Gi (Advanced)',
    competitionTraining: 'Competition Training',
    proTraining: 'Pro Training',
    other: 'Other',
  },
  noData: {
    title: 'No Gyms Found',
    messageLine1: 'No gyms match your current filters.',
    messageLine2: 'Try a different county or check back later.',
  },
  search: {
    label: 'Search gyms',
    placeholder: 'Search gyms...',
    clearLabel: 'Clear search',
    noResultsTitle: 'No gyms match your search',
    noResultsMessage: 'Try a different search term or clear the filter.',
    resultsSrPrefix: 'Showing',
    resultsSrSuffix: 'gyms',
  },
  card: {
    imageAlt: 'Exterior or interior of',
    fallbackName: 'Unnamed Gym',
    fallbackRef: 'this gym',
    detailsSrLabel: 'Details for',
    affiliatedWithLabel: 'Affiliated with',
    viewTimetableLink: 'View Timetable',
    offeredClassesLabel: 'Offered Classes',
    visitWebsiteButton: 'Visit Website',
    noWebsiteButton: 'Website Unavailable',
    trialOfferFallback: 'Trial offer available (details not specified)',
    trialOfferAriaPrefix: 'Trial Offer:',
  },
} as const
