name: 'Test React Application (Browser)'
description: 'Installs dependencies and runs Vitest browser tests inside the official Playwright container'
inputs:
  working-directory:
    description: 'Directory of the React application (where package.json is)'
    required: true
runs:
  using: "composite"
  steps:
    - name: Cache npm
      uses: actions/cache@0057852bfaa89a56745cba8c7296529d2fc39830  # v4
      with:
        path: ~/.npm
        key: ${{ runner.os }}-npm-${{ hashFiles('**/package-lock.json') }}
        restore-keys: ${{ runner.os }}-npm-

    - name: Install Dependencies
      shell: bash
      working-directory: ${{ inputs.working-directory }}
      run: npm ci

    - name: Run Browser Tests
      shell: bash
      working-directory: ${{ inputs.working-directory }}
      run: npm run test:browser

    - name: Upload Playwright Traces
      if: failure()
      uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02  # v4
      with:
        name: playwright-traces
        path: ${{ inputs.working-directory }}/src/**/__traces__
        retention-days: 7

    - name: Upload Failure Screenshots
      if: failure()
      uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02  # v4
      with:
        name: playwright-screenshots
        path: ${{ inputs.working-directory }}/src/**/__screenshots__
        retention-days: 7
