trigger:
  branches:
    include:
      - main
  tags:
    include:
      - 'v*.*.*'
  paths:
    include:
      - '**'
    exclude:
      - "**.md"
      - "logs/**"
      - ".gitattributes"
      - ".gitignore"
      - "docs/**"

pr:
  branches:
    include:
      - main
  paths:
    include:
      - '**'
    exclude:
      - "**.md"
      - "logs/**"
      - ".gitattributes"
      - ".gitignore"
      - "docs/**"


variables:
  - group: DEVOPS-Infra-DevTest-Secrets
  - group: DEVOPS-Infra-DevTest-Config
  - group: AZURE-Infra-DevTest-Config
  - group: BjjEire-Frontend-Secrets
  - template: templates/variables/ci-variables.yml

stages:
  - template: templates/stages/build-and-test-stage.yml

  # - template: templates/stages/package-and-push-stage.yml