trigger:
  branches:
    include:
      - main
  tags:
    include:
      - 'v*.*.*'
  paths:
    include:
      - "src/**"
      - "tests/**"
      - ".ado/**"
      - "Directory.*.props"
      - "*.sln"

pr:
  branches:
    include:
      - main
  paths:
    include:
      - "src/**"
      - "tests/**"
      - ".ado/**"
      - "Directory.*.props"
      - "*.sln"


variables:
  - group: DEVOPS-Infra-DevTest-Secrets
  - group: DEVOPS-Infra-DevTest-Config
  - group: AZURE-Infra-DevTest-Config
  - group: BjjEire-Frontend-Secrets
  - template: templates/variables/ci-variables.yml

stages:
  - template: templates/stages/build-and-test-stage.yml

  # - template: templates/stages/package-and-push-stage.yml