trigger: none

schedules:
- cron: "0 3 * * *"
  displayName: Daily Flaky Test Sync with Azure Boards
  branches: { include: [main] }
  always: true

pool:
  vmImage: 'windows-latest'

variables:
  - group: DEVOPS-Infra-DevTest-Secrets 
  - group: DEVOPS-Infra-DevTest-Config
  - template: templates/variables/flaky-tests-variables.yml

jobs:
  - template: jobs/flaky-test-analysis-job.yml
    parameters:
      name: flaky_test_analysis
      displayName: 'Analyze and Sync Flaky Tests'
